export const strings = {
	smartPregnancy: "Smart pregnancy monitoring for Smart you",
	enterMobile: "Enter mobile number",
	continue: "Continue",
	and: "and",
	tappingInfo:
		"By tapping on the button below you confirm that you are 16 years of age or older, and you agree to our",
	tnc: "terms & condition",
	privacy: "privacy policy",
	verify: "Verify",
	enterOtp: "Enter OTP",
	otpSent: "OTP sent to",
	didntReceive: "Didn't receive code?",
	resendIn: "Resend in",
	resendCode: "Resend Code",
	letsKnow: "Let's know your better",
	yourName: "Your name",
	yourAge: "Your age",
	pregnancyWeek: "Pregnancy week",
	save: "Save",
	track: "Track",
	settings: "Settings",
	babyKickCounter: "Baby Kick Counter",
	babyHeartbeat: "Baby Heartbeat & NST",
	babyKicks: "Baby Kicks",
	kicks: "Kicks",
	first: "First",
	last: "Last",
	tapIcon:
		"Tap the icons below when your baby kicks. Count 20 kicks in less than 2 hours",
	viewPastRecords: "View Past Records",
	maxHrs: "Max 2 hrs",
	reset: "Reset",
	complete: "Complete",
	completeSession: "Complete Session",
	youSure: "Are you sure?",
	dataLost: "All the data of current session will be lost, are you sure?",
	sessionAuto: "Session Auto-Completed",
	sessionLastAuto:
		"We have auto-completed your last session as it exceeded 2 hours.",
	no: "No",
	yes: "Yes",
	records: "Records",
	date: "Date",
	start: "Start",
	duration: "Duration",
	takeScreenshot:
		"Please take a screenshot of this page and share report. We are working on making is easier.",
	information: "Information",
	profile: "Profile",
	shareFeedback: "Share feeback",
	aboutJanitri: "About Janitri",
	contactUs: "Contact us",
	appVersion: "App Version",
	fillDetails: "Please fill in the details below",
	logout: "Logout",
	areYouLogout: "Are you sure, you want to logout?",
	newUpdateAvailable: "New update available",
	updateNow: "Update Now",
	comingSoonMsg:
		"We are currently developing this feature and will make sure to release it as soon as possible.\n\nMeanwhile, it is available on the Android App.\n\nThank you for your patience and understanding.",
	deleteAccount: "Delete Account",
	sureDeleteAccount: "Are you sure you want to delete your account?",
	cancel: "Cancel",
	ok: "Ok",
	contactJanitri:
		"Please contact Janitri(info@janitri.in) for recreation of your account.",
};
